language: node_js

# Notifications
notifications:
  email: false
  webhooks: 
    urls: 
      - http://efyges.ddns.net/travisci
    on_success: always
    on_failure: never
    on_start: never

# Branches to run
branches:
  only:
    - develop
    - master

# Versions to test
node_js:
  - 7.5
  - 6.1

# Gulp build and run tests
before_script:
  - npm install -g gulp
script: gulp test